apiVersion: v1
kind: Pod
metadata:
  namespace: arts-dev
spec:
  serviceAccountName: jenkins
  containers:
    - name: kubectl
      image: roffe/kubectl
      imagePullPolicy: Always
      command: ['cat']
      tty: true

    - name: maven
      image: maven:3.8.5-openjdk-17
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      
       

    - name: docker
      image: docker:20-dind
      securityContext:
        privileged: true
      imagePullPolicy: Always
      command: ['cat']
      tty: true
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
    